#GDC makefile.

DC = gdc
DFLAGS = -Wall -Wextra -pedantic -Isrc
GDB = -funittest -fdebug -ggdb3
DLDLIBS = -Llib -ledit -ltermcap

VPATH = src:src/ASM:src/utils

OBJS = main.o readline.o interpreter.o lexer.o parser.o AST.o kit.o lexical.o testing.o exception.o ctfe.o

TARGET = asm

all : $(TARGET)

$(TARGET) : $(OBJS)
	$(DC) $^ $(DLDLIBS) -o$@

%.o : %.d
	$(DC) $(DFLAGS) $(GDB) $< -c

clean:
	rm -f $(TARGET)
	rm -f *.o