#DMD makefile.

AR = ar
DC = dmd
DFLAGS = -wi -Isrc
GDB = -unittest -debug -gc
DLDLIBS = -L-Llib -L-L. -L-lasm

VPATH = src:src/dasm:src/utils

LIBOBJS = vm.o lexer.o parser.o ast.o kit.o lexical.o testing.o exception.o ctfe.o
OBJS = main.o

LIB = libasm.a
TARGET = asm

all : $(LIB) $(TARGET)

$(TARGET) : $(OBJS)
	$(DC) $^ $(DLDLIBS) -of$@

$(LIB) : $(LIBOBJS)
	$(AR) rc $@ $^

%.o : %.d
	$(DC) $(DFLAGS) $(GDB) $< -c

clean:
	rm -f $(LIB)
	rm -f $(TARGET)
	rm -f *.o
