#GDC makefile.

AR = ar
DC = gdc
DFLAGS = -Wall -Wextra -pedantic -Isrc
GDB = -funittest -fdebug -ggdb3
DLDLIBS = -Llib -L. -lasm

VPATH = src:src/ASM:src/utils

LIBOBJS = interpreter.o lexer.o parser.o AST.o kit.o lexical.o testing.o exception.o ctfe.o
OBJS = main.o

LIB = libasm.a
TARGET = asm

all : $(LIB) $(TARGET)

$(TARGET) : $(OBJS)
	$(DC) $^ $(DLDLIBS) -o$@

$(LIB) : $(LIBOBJS)
	$(AR) rc $@ $^

%.o : %.d
	$(DC) $(DFLAGS) $(GDB) $< -c

clean:
	rm -f $(LIB)
	rm -f $(TARGET)
	rm -f *.o
