#DMD makefile.

DC = dmd
DFLAGS = -wi -Isrc
GDB = -unittest -debug -gc
DLDLIBS = -L-Llib -L-ledit -L-ltermcap

VPATH = src:src/ASM:src/utils

OBJS = main.o readline.o interpreter.o lexer.o parser.o AST.o kit.o lexical.o testing.o exception.o ctfe.o

TARGET = asm

all : $(TARGET)

$(TARGET) : $(OBJS)
	$(DC) $^  $(DLDLIBS) -of$@

%.o : %.d
	$(DC) $(DFLAGS) $(GDB) $< -c

clean:
	rm -f $(TARGET)
	rm -f *.o
